name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build - tonidz/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
         env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASWWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push tonidz/auth
      - uses: digitalocean/action-doctl@v2
         with:
           token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kuberconfig save ticketing
      - run: kubectl rollout restart deployment auth-depl
