name: deploy-manifests
on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 8cbf4ca7-70b4-4120-8cf4-ede452cbb162
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
